### ISSUE TITLE
Links not hidden by Cloze

### ISSUE THREAD

**Issue by apangasa** [DearVikki/obsidian-cloze-plugin#14] opened 2023-12-29 00:19 UTC
Hi, I'm finding this plugin very useful, and it is almost perfect for my needs, but it does not hide text contained in double brackets. I'm using this to "spoiler" large sections of text that have numerous links, so this is an issue for me. Perhaps this is simply a matter of changing the link color when the cloze is toggled. Please let me know if this is possible to fix. Thanks!

**Comment by DearVikki** [comment] 2023-12-29 06:59
Hi @apangasa, thank you for reporting this 🐞, this is exactly the meaning of GitHub issues! I've already found the cause of this bug (yes you guessed it right! Its simply a matter of hiding the internal link as well). I'll let you know as soon as it's fixed in the next version. :D

**Comment by apangasa** [comment] 2023-12-29 21:46
Thanks so much!

**Comment by DearVikki** [comment] 2023-12-30 16:02
Hi @apangasa, now you can find the latest release (version 0.1.11) and I hope it works all well for you!

**Comment by 1chevre** [comment] 2023-12-30 16:25
Wow you are so efficient! Thank you for the fix, I'm enjoying your plugin, exactly what I needed!

**Closed** 2023-12-31 07:26 UTC
